// <auto-generated />
namespace RequestWorkflow.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedCommentmodelandlinkedittoEvent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedCommentmodelandlinkedittoEvent));
        
        string IMigrationMetadata.Id
        {
            get { return "201707171236186_added Comment model and linked it to Event"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
